### ISSUE TITLE
Stop processing when a test case failed

### ISSUE THREAD

**Issue by pacroy** [chonla/cotton#16]
Can we have an option to stop processing when a test case is failed. Like `--bail` option in [newman](https://learning.getpostman.com/docs/postman/collection_runs/command_line_integration_with_newman/).

Suppose an MD file contains 5 test cases, if the first case fail then the other 4 cases should not be run. This is to avoid being detected as DoS attack.

**Comment by chonla** [comment]
Done in 0.3.1 (b03ea1cb0e3bfefb0eda3d420a1f6df058bc7c90). Thank you for your suggestion.
