### ISSUE TITLE
Passing in variables from command line

### ISSUE THREAD

**Issue by pacroy** [chonla/cotton#6]
Putting credential in the test script is not a good idea.

Can we passing in variables from the command line? like this:

`cotton -u https://somedomain.com -f token=abc123 tests.md`

and in the script we can substitute with variable like this:

| Header | Value |
| - | - |
| Authorization | Basic {token} |

**Comment by chonla** [comment]
Done in ceee1747ee36a118c26ed91e93293005307edea6
