### ISSUE TITLE
URI is not automatically encoded

### ISSUE THREAD

**Issue by pacroy** [chonla/cotton#8]
URIs must be encoded in the test scripts making them harder to read.

For example:  
NOT WORKING:  `## GET /customer?search=ทดสอบ`  
WORKING: `## GET /customer?search=%E0%B8%97%E0%B8%94%E0%B8%AA%E0%B8%AD%E0%B8%9A`  
  
NOT WORKING: `## GET /customer?filter=Name+eq+'Test Customer'`  
WORKING: `## GET /customer?filter=Name+eq+'Test%20Customer'`

**Comment by chonla** [comment]
Fixed in a5d113406a0753dbab717aeb74298889d39680c1.

FYI, + and %20 are the same thing. So `/customer?filter=Name+eq+'Test Customer'` will be escaped to `/customer?filter=Name+eq+'Test+Customer'`.

**Comment by pacroy** [comment]
Tested with https://gist.github.com/pacroy/a05582d2f6dfe28043a20bdcece83373 and look great. Thank you!

**Comment by chonla** [comment]
No problem. Thank you for keep feedbacking. 👍
